/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <string.h>
#include "rpc.h"

void innerproductprog_1(int newsockfd, char *host, int n, int *x, int *y)
{
	CLIENT *clnt;
	int *result_1;
	dataOne innerproduct_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, INNERPRODUCTPROG, KEKW, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	/* Start of custom code */
	int result;
	innerproduct_1_arg.n = n;
	innerproduct_1_arg.x.x_len = n;
	innerproduct_1_arg.y.y_len = n;
	innerproduct_1_arg.x.x_val = (int *)malloc(n * sizeof(int));
	innerproduct_1_arg.y.y_val = (int *)malloc(n * sizeof(int));

	// Copy values of x and y arrays
	for (int i = 0; i < n; i++)
	{
		innerproduct_1_arg.x.x_val[i] = x[i];
		innerproduct_1_arg.y.y_val[i] = y[i];
	}
	/* End of custom code */

	result_1 = innerproduct_1(&innerproduct_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	/* Start of custom code */
	result = *result_1;
	send(newsockfd, &result, sizeof(int), 0);
	/* End of custom code */

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

void averageprog_1(int newsockfd, char *host, int n, int *x, int *y)
{
	CLIENT *clnt;
	resultVector *result_1;
	dataOne average_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, AVERAGEPROG, KEKW, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	/* Start of custom code */
	average_1_arg.n = n;
	average_1_arg.x.x_len = n;
	average_1_arg.y.y_len = n;
	average_1_arg.x.x_val = (int *)malloc(n * sizeof(int));
	average_1_arg.y.y_val = (int *)malloc(n * sizeof(int));

	// Copy values of x and y arrays
	for (int i = 0; i < n; i++)
	{
		average_1_arg.x.x_val[i] = x[i];
		average_1_arg.y.y_val[i] = y[i];
	}
	/* End of custom code */

	result_1 = average_1(&average_1_arg, clnt);
	if (result_1 == (resultVector *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	/* Start of custom code */
	double *resultArray = (double *)malloc(sizeof(double) * 2);
	resultArray[0] = result_1->result.result_val[0];
	resultArray[1] = result_1->result.result_val[1];
	send(newsockfd, resultArray, sizeof(double) * 2, 0);
	free(resultArray);
	free(average_1_arg.x.x_val);
	free(average_1_arg.y.y_val);
	/* Stop of custom code */

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

void multiplicationprog_1(int newsockfd, char *host, int n, int *x, int *y, double r)
{
	CLIENT *clnt;
	resultVector *result_1;
	dataTwo multiplication_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, MULTIPLICATIONPROG, KEKW, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	/* Start of custom code */
	double *resultArray;
	multiplication_1_arg.n = n;
	multiplication_1_arg.r = r;
	multiplication_1_arg.x.x_len = n;
	multiplication_1_arg.y.y_len = n;
	multiplication_1_arg.x.x_val = (int *)malloc(n * sizeof(int));
	multiplication_1_arg.y.y_val = (int *)malloc(n * sizeof(int));

	// Copy values of x and y arrays
	for (int i = 0; i < n; i++)
	{
		multiplication_1_arg.x.x_val[i] = x[i];
		multiplication_1_arg.y.y_val[i] = y[i];
	}
	/* Stop of custom code */

	result_1 = multiplication_1(&multiplication_1_arg, clnt);
	if (result_1 == (resultVector *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	/* Start of custom code */
	double *resultArrayR = (double *)malloc(sizeof(double) * n);
	for (int i = 0; i < n; i++)
	{
		resultArrayR[i] = result_1->result.result_val[i];
	}
	send(newsockfd, resultArrayR, sizeof(double) * n, 0);
	free(resultArrayR);
	free(multiplication_1_arg.x.x_val);
	free(multiplication_1_arg.y.y_val);
	/* Stop of custom code */

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
    char *host;
    int sockfd, newsockfd, portno, clilen;
    pid_t procId;
    struct sockaddr_in serv_addr, cli_addr;

    if (argc < 3)
    {
        printf("Usage: %s server_host port_number\n", argv[0]);
        exit(1);
    }

    host = argv[1];
    portno = atoi(argv[2]);

    // Create a socket
    sockfd = socket(AF_INET, SOCK_STREAM, 0);
    if (sockfd < 0)
    {
        perror("An error occurred while opening socket.\n");
        exit(1);
    }
    bzero((char *)&serv_addr, sizeof(serv_addr));
    serv_addr.sin_family = AF_INET;
    serv_addr.sin_port = htons(portno);
    serv_addr.sin_addr.s_addr = INADDR_ANY;

    // Bind the socket to the server address
    if (bind(sockfd, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) < 0)
    {
        perror("An error occurred while binding.\n");
        exit(1);
    }

    // Listen for incoming connections
    listen(sockfd, 5);

    for (;;)
    {
        clilen = sizeof(cli_addr);

        // Accept a new connection
        newsockfd = accept(sockfd, (struct sockaddr *)&cli_addr, &clilen);
        if (newsockfd < 0)
        {
            perror("An error occurred. Connection could not be accepted.\n");
            exit(1);
        }

        if (fork() == 0)
        { // Create Child process
            close(sockfd); // Close Socket because we don't need it anymore
            printf("Connection Established.\n");

            int n, option;
            int *x, *y;
            double r;
            int end = 0;

            // Receive data from the client
            recv(newsockfd, &n, sizeof(int), 0);

            x = (int *)malloc(n * sizeof(int));
            y = (int *)malloc(n * sizeof(int));

            recv(newsockfd, &r, sizeof(double), 0);
            recv(newsockfd, x, sizeof(int) * n, 0);
            recv(newsockfd, y, sizeof(int) * n, 0);

            while (!end)
            {
                // Receive the option from the client
                recv(newsockfd, &option, sizeof(int), 0);

                switch (option)
                {
                case 1:
                    printf("Requesting inner product from the server...\n");
                    innerproductprog_1(newsockfd, host, n, x, y);
                    printf("Received inner product from the server.\n");
                    break;
                case 2:
                    printf("Requesting average from the server...\n");
                    averageprog_1(newsockfd, host, n, x, y);
                    printf("Received average from the server.\n");
                    break;
                case 3:
                    printf("Requesting r*(X+Y) from the server...\n");
                    multiplicationprog_1(newsockfd, host, n, x, y, r);
                    printf("Received r*(X+Y) from the server.\n");
                    break;
                case 4:
                    printf("Connection terminated.\n");
                    end = 1;
                    break;
                }
            }

            close(newsockfd);
            free(x);
            free(y);
            exit(0);
        }
        else
        {
            close(newsockfd);
    }
}

/* Close the main socket */
close(sockfd);

exit(0);
}
