
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = rpc_client
SERVER = rpc_server

# Start of custom command
SOCKET_CLIENT = socket_client
# End of custom command

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = rpc.x

TARGETS_SVC.c = rpc_svc.c rpc_server.c rpc_xdr.c 
TARGETS_CLNT.c = rpc_clnt.c rpc_client.c rpc_xdr.c 
TARGETS = rpc.h rpc_xdr.c rpc_clnt.c rpc_svc.c rpc_client.c rpc_server.c

# Start of custom command
TARGET_CLIENT = socket_client.c
# Start of custom command

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)

# Compiler flags 

CFLAGS += -g 
LDLIBS += -lnsl
RPCGENFLAGS = 

# Start of custom command
CFLAGS += -I/usr/include/tirpc
LDLIBS += -ltirpc
# End of custom command

# Targets 

all : $(CLIENT) $(SERVER) $(SOCKET_CLIENT) # Custom command

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

# Start of custom command 
$(SOCKET_CLIENT): $(TARGET_CLIENT)
	$(CC) -o $(SOCKET_CLIENT) $(TARGET_CLIENT)
# End of custom command 

 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER)

