/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dataOne {
	int n;
	struct {
		u_int x_len;
		int *x_val;
	} x;
	struct {
		u_int y_len;
		int *y_val;
	} y;
};
typedef struct dataOne dataOne;

struct dataTwo {
	int n;
	double r;
	struct {
		u_int x_len;
		int *x_val;
	} x;
	struct {
		u_int y_len;
		int *y_val;
	} y;
};
typedef struct dataTwo dataTwo;

struct resultVector {
	struct {
		u_int result_len;
		double *result_val;
	} result;
};
typedef struct resultVector resultVector;

#define INNERPRODUCTPROG 0x69696901
#define KEKW 1

#if defined(__STDC__) || defined(__cplusplus)
#define innerProduct 1
extern  int * innerproduct_1(dataOne *, CLIENT *);
extern  int * innerproduct_1_svc(dataOne *, struct svc_req *);
extern int innerproductprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define innerProduct 1
extern  int * innerproduct_1();
extern  int * innerproduct_1_svc();
extern int innerproductprog_1_freeresult ();
#endif /* K&R C */

#define AVERAGEPROG 0x69696902
#define KEKW 1

#if defined(__STDC__) || defined(__cplusplus)
#define average 1
extern  resultVector * average_1(dataOne *, CLIENT *);
extern  resultVector * average_1_svc(dataOne *, struct svc_req *);
extern int averageprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define average 1
extern  resultVector * average_1();
extern  resultVector * average_1_svc();
extern int averageprog_1_freeresult ();
#endif /* K&R C */

#define MULTIPLICATIONPROG 0x69696903
#define KEKW 1

#if defined(__STDC__) || defined(__cplusplus)
#define multiplication 1
extern  resultVector * multiplication_1(dataTwo *, CLIENT *);
extern  resultVector * multiplication_1_svc(dataTwo *, struct svc_req *);
extern int multiplicationprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define multiplication 1
extern  resultVector * multiplication_1();
extern  resultVector * multiplication_1_svc();
extern int multiplicationprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dataOne (XDR *, dataOne*);
extern  bool_t xdr_dataTwo (XDR *, dataTwo*);
extern  bool_t xdr_resultVector (XDR *, resultVector*);

#else /* K&R C */
extern bool_t xdr_dataOne ();
extern bool_t xdr_dataTwo ();
extern bool_t xdr_resultVector ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
